require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/inscriptions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Inscription. As you add validations to Inscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Inscription.create! valid_attributes
      get inscriptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      inscription = Inscription.create! valid_attributes
      get inscription_url(inscription)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_inscription_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      inscription = Inscription.create! valid_attributes
      get edit_inscription_url(inscription)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Inscription" do
        expect {
          post inscriptions_url, params: { inscription: valid_attributes }
        }.to change(Inscription, :count).by(1)
      end

      it "redirects to the created inscription" do
        post inscriptions_url, params: { inscription: valid_attributes }
        expect(response).to redirect_to(inscription_url(Inscription.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Inscription" do
        expect {
          post inscriptions_url, params: { inscription: invalid_attributes }
        }.to change(Inscription, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post inscriptions_url, params: { inscription: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested inscription" do
        inscription = Inscription.create! valid_attributes
        patch inscription_url(inscription), params: { inscription: new_attributes }
        inscription.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the inscription" do
        inscription = Inscription.create! valid_attributes
        patch inscription_url(inscription), params: { inscription: new_attributes }
        inscription.reload
        expect(response).to redirect_to(inscription_url(inscription))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        inscription = Inscription.create! valid_attributes
        patch inscription_url(inscription), params: { inscription: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested inscription" do
      inscription = Inscription.create! valid_attributes
      expect {
        delete inscription_url(inscription)
      }.to change(Inscription, :count).by(-1)
    end

    it "redirects to the inscriptions list" do
      inscription = Inscription.create! valid_attributes
      delete inscription_url(inscription)
      expect(response).to redirect_to(inscriptions_url)
    end
  end
end
